In [1]:
import numpy as np
import pandas as pd

In [2]:
import requests
import xlsxwriter
import math

In [3]:
nifty=pd.read_csv('NIFTY.csv')

In [4]:
nifty.columns

Index(['SYMBOL \n', 'OPEN \n', 'HIGH \n', 'LOW \n', 'PREV. CLOSE \n', 'LTP \n',
       'CHNG \n', '%CHNG \n', 'VOLUME \n(shares)', 'VALUE ', '52W H \n',
       '52W L \n', '365 D % CHNG \n 02-Mar-2022',
       '30 D % CHNG \n 31-Jan-2023'],
      dtype='object')

In [5]:
data = pd.DataFrame(nifty[['SYMBOL \n','LTP \n','VALUE ']])
type(data)

pandas.core.frame.DataFrame

In [6]:
data=data.drop(index=0)

In [7]:
data['shares to buy']=np.nan

In [8]:
data

     SYMBOL \n     LTP \n             VALUE   shares to buy
1     ADANIENT   2,068.65  26,840,005,620.51            NaN
2   ADANIPORTS     704.35  15,254,403,734.14            NaN
3    POWERGRID     228.25   1,252,751,035.12            NaN
4         NTPC     177.20     996,156,967.40            NaN
5         INFY   1,515.50   4,445,911,851.84            NaN
6         ONGC     158.00     796,428,801.00            NaN
7   BAJAJFINSV   1,386.90   1,790,201,162.40            NaN
8   TATAMOTORS     437.30   1,848,382,860.00            NaN
9   ASIANPAINT   2,874.00   1,075,843,820.64            NaN
10       WIPRO     396.05     654,000,919.65            NaN
11         TCS   3,389.35   1,700,121,495.94            NaN
12        HDFC   2,682.55   5,151,568,384.96            NaN
13    RELIANCE   2,415.55   4,911,485,469.66            NaN
14         ITC     389.75   1,925,421,200.78            NaN
15        BPCL     325.25     341,957,980.54            NaN
16  BHARTIARTL     773.55   1,921,884,241.72            NaN
17  APOLLOHOSP   4,460.00     418,438,522.29            NaN
18  TATACONSUM     718.05     220,571,804.10            NaN
19         M&M   1,282.65     925,576,750.02            NaN
20   EICHERMOT   3,160.30     497,459,770.16            NaN
21   SUNPHARMA     976.95     818,267,328.01            NaN
22   COALINDIA     225.15     449,443,163.85            NaN
23  HEROMOTOCO   2,484.20     260,211,936.33            NaN
24    HDFCBANK   1,629.70  11,907,917,142.28            NaN
25    HDFCLIFE     494.05     631,389,521.11            NaN
26         UPL     715.55     328,297,917.75            NaN
27  BAJFINANCE   6,146.80   2,041,409,019.44            NaN
28     HCLTECH   1,127.40   2,878,660,696.00            NaN
29     SBILIFE   1,137.35     549,704,936.27            NaN
30  HINDUNILVR   2,487.95   1,066,752,724.52            NaN
31  BAJAJ-AUTO   3,757.35     342,659,038.44            NaN
32    AXISBANK     858.30   3,872,786,814.90            NaN
33    DIVISLAB   2,868.20     226,897,855.47            NaN
34      GRASIM   1,605.70     223,616,713.44            NaN
35       TITAN   2,407.05     718,348,896.25            NaN
36      MARUTI   8,632.40     886,120,952.10            NaN
37       CIPLA     881.80   2,382,267,557.04            NaN
38    HINDALCO     418.25     985,945,845.30            NaN
39       TECHM   1,088.55   1,287,480,429.93            NaN
40        SBIN     562.95   5,152,452,388.93            NaN
41   NESTLEIND  18,500.00     374,752,798.30            NaN
42     DRREDDY   4,447.30     201,582,155.88            NaN
43          LT   2,155.95   1,938,194,170.12            NaN
44   TATASTEEL     107.15   2,698,105,037.90            NaN
45  INDUSINDBK   1,127.20   2,351,547,889.34            NaN
46  ULTRACEMCO   7,207.90     422,159,950.32            NaN
47   ICICIBANK     867.55   6,204,427,596.08            NaN
48   KOTAKBANK   1,748.65   4,636,668,817.66            NaN
49    JSWSTEEL     680.00     382,947,800.72            NaN
50   BRITANNIA   4,293.55   1,702,886,426.31            NaN

In [31]:
portfolio_size= float(input('enter the value of your portfolio: '))
import re

In [63]:
position_size= portfolio_size/len(data)
for i in range(1,len(data)+1):
    a = data.loc[i,'LTP \n']
    if ',' in a:
       a=a.replace(',','')
       a=float(a)
    else:
        a=float(a)
    data.loc[i,'shares to buy']=position_size//a
data

     SYMBOL \n     LTP \n             VALUE   shares to buy
1     ADANIENT   2,068.65  26,840,005,620.51           96.0
2   ADANIPORTS     704.35  15,254,403,734.14          283.0
3    POWERGRID     228.25   1,252,751,035.12          876.0
4         NTPC     177.20     996,156,967.40         1128.0
5         INFY   1,515.50   4,445,911,851.84          131.0
6         ONGC     158.00     796,428,801.00         1265.0
7   BAJAJFINSV   1,386.90   1,790,201,162.40          144.0
8   TATAMOTORS     437.30   1,848,382,860.00          457.0
9   ASIANPAINT   2,874.00   1,075,843,820.64           69.0
10       WIPRO     396.05     654,000,919.65          504.0
11         TCS   3,389.35   1,700,121,495.94           59.0
12        HDFC   2,682.55   5,151,568,384.96           74.0
13    RELIANCE   2,415.55   4,911,485,469.66           82.0
14         ITC     389.75   1,925,421,200.78          513.0
15        BPCL     325.25     341,957,980.54          614.0
16  BHARTIARTL     773.55   1,921,884,241.72          258.0
17  APOLLOHOSP   4,460.00     418,438,522.29           44.0
18  TATACONSUM     718.05     220,571,804.10          278.0
19         M&M   1,282.65     925,576,750.02          155.0
20   EICHERMOT   3,160.30     497,459,770.16           63.0
21   SUNPHARMA     976.95     818,267,328.01          204.0
22   COALINDIA     225.15     449,443,163.85          888.0
23  HEROMOTOCO   2,484.20     260,211,936.33           80.0
24    HDFCBANK   1,629.70  11,907,917,142.28          122.0
25    HDFCLIFE     494.05     631,389,521.11          404.0
26         UPL     715.55     328,297,917.75          279.0
27  BAJFINANCE   6,146.80   2,041,409,019.44           32.0
28     HCLTECH   1,127.40   2,878,660,696.00          177.0
29     SBILIFE   1,137.35     549,704,936.27          175.0
30  HINDUNILVR   2,487.95   1,066,752,724.52           80.0
31  BAJAJ-AUTO   3,757.35     342,659,038.44           53.0
32    AXISBANK     858.30   3,872,786,814.90          233.0
33    DIVISLAB   2,868.20     226,897,855.47           69.0
34      GRASIM   1,605.70     223,616,713.44          124.0
35       TITAN   2,407.05     718,348,896.25           83.0
36      MARUTI   8,632.40     886,120,952.10           23.0
37       CIPLA     881.80   2,382,267,557.04          226.0
38    HINDALCO     418.25     985,945,845.30          478.0
39       TECHM   1,088.55   1,287,480,429.93          183.0
40        SBIN     562.95   5,152,452,388.93          355.0
41   NESTLEIND  18,500.00     374,752,798.30           10.0
42     DRREDDY   4,447.30     201,582,155.88           44.0
43          LT   2,155.95   1,938,194,170.12           92.0
44   TATASTEEL     107.15   2,698,105,037.90         1866.0
45  INDUSINDBK   1,127.20   2,351,547,889.34          177.0
46  ULTRACEMCO   7,207.90     422,159,950.32           27.0
47   ICICIBANK     867.55   6,204,427,596.08          230.0
48   KOTAKBANK   1,748.65   4,636,668,817.66          114.0
49    JSWSTEEL     680.00     382,947,800.72          294.0
50   BRITANNIA   4,293.55   1,702,886,426.31           46.0

In [64]:
writer = pd.ExcelWriter('recommended trades.xlsx', engine='xlsxwriter')
data.to_excel(writer, 'Recommended Trades', index=False)

In [65]:
data.to_excel('recommended trades.xlsx')